### PR TITLE
fix(feline): use new `vim.lsp.status()` method

### LINKED ISSUE #508: Feline not updated to nvim 0.10
### Description

feline integration not working on nvim 0.10

this is due to `vim.lsp.util.get_progress_messages` being deprecated [see here](https://github.com/neovim/neovim/blob/a7e5d4238a00d5bfa5809b2860047eca2d565e62/runtime/doc/news.txt#L151-L152)

`vim.lsp.status` should be used instead

### Neovim version

```markdown
NVIM v0.10.0-dev-499+g643546b82
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Terminal and multiplexer

kitty 0.28.1

### Catppuccin version / branch / rev

head

### Steps to reproduce

update neovim to lastest nightly release
run it

### Expected behavior

just works

### Actual behavior

Error message
image

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "catppuccin/nvim",
  "famiu/feline.nvim"
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
-- add anything else here

local ctp_feline = require('catppuccin.groups.integrations.feline')

ctp_feline.setup{}

require("feline").setup({
    components = ctp_feline.get(),
})
```

### PR DESCRIPTION
**Pull request by mrtnvgr**
Fixes #508

### CODE REVIEW

File: lua/catppuccin/groups/integrations/feline.lua [hunk 1]
```diff
@@ -292,7 +292,8 @@ function M.get()
 	-- workspace loader
 	components.active[2][1] = {
 		provider = function()
-			local Lsp = vim.lsp.util.get_progress_messages()[1]
+			-- local Lsp = vim.lsp.status()[1]
+			local Lsp = vim.fn.has "neovim-0.10" == 1 and vim.lsp.util.get_progress_messages()[1] or vim.lsp.status()[1]
```
Comment (lucario387) [inline lua/catppuccin/groups/integrations/feline.lua:296]: Uhh, this returns 0, so this breaks for neovim-stable users

Comment (nekowinston) [reply lua/catppuccin/groups/integrations/feline.lua:296]: Yeah, this errors for me on 0.9.1, this works:
```suggestion
			local Lsp
			if vim.fn.has "neovim-0.10" then
				Lsp = vim.lsp.util.get_progress_messages()[1]
			else
				Lsp = vim.lsp.status()[1]
			end
```

File: lua/catppuccin/groups/integrations/feline.lua [hunk 2]
```diff
@@ -292,7 +292,12 @@ function M.get()
 	-- workspace loader
 	components.active[2][1] = {
 		provider = function()
-			local Lsp = vim.lsp.util.get_progress_messages()[1]
+			local Lsp
+			if vim.fn.has "neovim-0.10" then
```
Comment (lucario387) [inline lua/catppuccin/groups/integrations/feline.lua:296]: This is still wrong. It should be `vim.fn.has "nvim-0.10" == 1` as 0 is considered true in lua
